import fs from 'node:fs'
import path from 'node:path'

const root = '/home/ubuntu/universe-sent-me-growth-os'
const readMcp = (file) => JSON.parse(JSON.parse(fs.readFileSync(file, 'utf8')).content[0].text)
const ig = readMcp('/home/ubuntu/.mcp/tool-results/2026-08-19_16-03-28.365303385_windsor-ai_get_data_1fb72e4d.json')
const tikTok = readMcp('/home/ubuntu/.mcp/tool-results/2026-08-19_16-03-55.912029412_windsor-ai_get_data_37b1914b.json')
const youtubeDaily = readMcp('/home/ubuntu/.mcp/tool-results/2026-08-19_16-04-21.644737879_windsor-ai_get_data_32c91bf7.json')
const youtubeLifetime = readMcp('/home/ubuntu/.mcp/tool-results/2026-08-19_16-04-35.328699488_windsor-ai_get_data_065a944b.json')
const facebook = [
  ...readMcp('/home/ubuntu/.mcp/tool-results/2026-08-19_16-07-09.089260674_windsor-ai_get_data_7a74e6cd.json'),
  ...readMcp('/home/ubuntu/.mcp/tool-results/2026-08-19_16-07-20.484121557_windsor-ai_get_data_4b984ea5.json'),
]
const now = new Date().toISOString()
const n = (value) => Number.isFinite(Number(value)) ? Number(value) : null
const ytById = new Map(youtubeLifetime.map((row) => [row.video, row]))
const uniqueTikTok = new Map()
for (const row of tikTok.filter((row) => row.video_id)) uniqueTikTok.set(row.video_id, row)
const social = {
  title: 'Rendimiento social multicanal — corte 28 días', purpose: 'Dataset normalizado de publicaciones y métricas nativas para análisis comparativo; no fuerza equivalencias entre plataformas.', status: 'Active', created_at: '2026-08-19', last_updated: '2026-08-19', version: '1.1', author: 'Manus AI', related_documents: ['2026-08-19_Windsor_Facebook_Organic_28D_Normalizado.json', '../../GrowthOS/14_00_Fuente_Maestra_y_Ledgers.md'],
  cut: { start: '2026-07-22', end: '2026-08-18' }, retrieved_at: now,
  sources: ['Windsor.ai:instagram', 'Windsor.ai:tiktok_organic', 'Windsor.ai:youtube'],
  normalization_rules: ['One row per Instagram media_id and TikTok video_id after deduplication.', 'YouTube keeps daily_observed_activity separately from lifetime_current_snapshot.', 'No cross-platform totals are used as a performance verdict because metric definitions and windows differ.'],
  platforms: {
    Instagram: { content_rows: ig.map((row) => ({ platform: 'Instagram', account_id: row.account_id, account_name: row.account_name, content_id: row.media_id, published_at: row.timestamp, content_type: row.media_type === 'REELS' ? 'Reel' : row.media_type, caption: row.media_caption ?? '', views: n(row.media_views), reach: n(row.media_reach), likes: n(row.media_like_count), comments: n(row.media_comments_count), shares: n(row.media_shares), saves_or_favorites: n(row.media_saved), engagement: [row.media_like_count, row.media_comments_count, row.media_shares, row.media_saved].reduce((sum, x) => sum + (n(x) ?? 0), 0), avg_watch_time_seconds: n(row.media_reel_avg_watch_time) === null ? null : n(row.media_reel_avg_watch_time) / 1000, total_watch_time_seconds: n(row.media_reel_total_watch_time) === null ? null : n(row.media_reel_total_watch_time) / 1000, source: 'Windsor.ai:instagram', retrieved_at: now, window_type: 'lifetime_current_snapshot', comparability: 'within_platform_primary' })) },
    TikTok: { content_rows: [...uniqueTikTok.values()].map((row) => ({ platform: 'TikTok', account_id: row.account_id, account_name: row.account_name, content_id: row.video_id, published_at: row.video_create_datetime, content_type: 'Video', caption: row.video_caption ?? '', views: n(row.video_views_count), reach: null, likes: n(row.video_likes), comments: n(row.video_comments), shares: n(row.video_shares), saves_or_favorites: n(row.video_favorites), engagement: [row.video_likes, row.video_comments, row.video_shares, row.video_favorites].reduce((sum, x) => sum + (n(x) ?? 0), 0), avg_watch_time_seconds: n(row.video_average_time_watched), total_watch_time_seconds: n(row.video_total_time_watched), completion_rate: n(row.video_full_watched_rate), followers_gained: n(row.video_new_followers), source: 'Windsor.ai:tiktok_organic', retrieved_at: now, window_type: 'lifetime_current_snapshot', comparability: 'within_platform_primary' })) },
    YouTube: { daily_rows: youtubeDaily.map((row) => ({ platform: 'YouTube', account_id: row.account_id, account_name: row.account_name, content_id: row.video, date: row.date, title: ytById.get(row.video)?.video_title ?? row.video, views: n(row.views), likes: n(row.likes), comments: n(row.comments), shares: 0, subscribers_gained: n(row.subscribers_gained), subscribers_lost: n(row.subscribers_lost), average_view_percentage: n(row.average_view_percentage), source: 'Windsor.ai:youtube', retrieved_at: now, window_type: 'daily_observed_activity', comparability: 'within_platform_primary' })), lifetime_snapshots: youtubeLifetime.map((row) => ({ platform: 'YouTube', account_id: row.account_id, account_name: row.account_name, content_id: row.video, title: row.video_title, published_at: row.published_at, lifetime_views_snapshot: n(row.video_view_count), likes_snapshot: n(row.video_like_count), comments_snapshot: n(row.video_comment_count), url: row.videourl, source: 'Windsor.ai:youtube', retrieved_at: now, window_type: 'lifetime_current_snapshot', comparability: 'display_only_not_additive' })) },
  },
}
const facebookArtifact = { title: 'Facebook orgánico — corte 28 días normalizado', purpose: 'Preservar filas por publicación de Facebook con la métrica canónica reacciones + comentarios + shares.', status: 'Active', created_at: '2026-08-19', last_updated: '2026-08-19', version: '1.1', author: 'Manus AI', related_documents: ['2026-08-19_Social_Performance_28D_Normalizado.json', '../../GrowthOS/14_00_Fuente_Maestra_y_Ledgers.md'], source: 'Windsor.ai', connector: 'facebook_organic', account_id: '1036844829507460', account_name: 'Universe Sent Me', cut: social.cut, retrieved_at: now, row_count: facebook.length, rows: facebook.sort((a,b) => `${a.date}|${a.post_id}`.localeCompare(`${b.date}|${b.post_id}`)), metric_definition: 'post_reactions_total + post_comments_total + post_activity_by_action_type_share; post_engagements is retained only outside this artifact and is not used.' }
fs.writeFileSync(path.join(root, 'Operations/Research/2026-08-19_Social_Performance_28D_Normalizado.json'), JSON.stringify(social, null, 2) + '\n')
fs.writeFileSync(path.join(root, 'Operations/Research/2026-08-19_Windsor_Facebook_Organic_28D_Normalizado.json'), JSON.stringify(facebookArtifact, null, 2) + '\n')
console.log(JSON.stringify({ cut: social.cut, instagram: social.platforms.Instagram.content_rows.length, tiktok: social.platforms.TikTok.content_rows.length, youtubeDaily: social.platforms.YouTube.daily_rows.length, youtubeSnapshots: social.platforms.YouTube.lifetime_snapshots.length, facebook: facebookArtifact.row_count }, null, 2))
