import pandas as pd
from pathlib import Path
import json
root=Path('/home/ubuntu/universe-sent-me-growth-os')
inv=pd.read_csv(root/'GrowthOS/Content_Inventory.csv',dtype=str).fillna('')
pub=pd.read_csv(root/'Operations/Research/2026-08-15_Publication_Log.csv',dtype=str).fillna('')
exp=pd.read_csv(root/'Operations/Research/2026-08-15_ExperimentLog.csv',dtype=str).fillna('')
p0=pd.read_csv(root/'Operations/Research/2026-08-17_P0_Baseline_Ola_Activa.csv',dtype=str).fillna('')
cal=pd.read_csv(root/'Operations/Research/2026-08-16_Calendario_Operativo_17_30_Agosto.csv',dtype=str).fillna('')
print('INVENTORY rows',len(inv),'CNT duplicate',inv.CNT_ID.duplicated().sum() if 'CNT_ID' in inv else 'missing')
print('INVENTORY Asset_Ref duplicate nonblank',inv.loc[inv.Asset_Ref.ne(''),'Asset_Ref'].duplicated().sum() if 'Asset_Ref' in inv else 'missing')
print('PUBLICATION states'); print(pub['Estado_Publicacion'].value_counts(dropna=False).to_string())
print('PUBLICATION platforms'); print(pub['Plataforma'].value_counts(dropna=False).to_string())
print('PUBLICATION experiments'); print(pub['Experiment_ID'].value_counts(dropna=False).to_string())
print('EXPERIMENT IDs'); print(exp['Experiment_ID'].value_counts(dropna=False).to_string())
print('P0 window status'); print(p0['window_status'].value_counts(dropna=False).to_string())
print('P0 missing metrics rows',p0['interactions_24h'].eq('').sum(),p0['interactions_72h'].eq('').sum())
print('CALENDAR rows/status'); print(len(cal),cal['Estado'].value_counts(dropna=False).to_string())
print('CALENDAR dates',cal['Fecha'].min(),cal['Fecha'].max(),'slots',cal['Hora'].nunique())
print('--- broken links ---')
inv_assets=set(inv.Asset_Ref[inv.Asset_Ref.ne('')])
pub_assets=set(pub.Asset_Ref[pub.Asset_Ref.ne('')])
print('pub asset refs absent inventory',len(pub_assets-inv_assets),sorted(pub_assets-inv_assets))
inv_ids=set(inv.id[inv.id.ne('')])
p0_assets=set(p0.Asset_Ref[p0.Asset_Ref.ne('')])
print('p0 assets absent inventory by Asset_Ref',len(p0_assets-inv_assets),sorted(p0_assets-inv_assets))
print('p0 Asset_Refs matching inventory id',len(p0_assets & inv_ids),sorted(p0_assets & inv_ids))
pub_exp=set(pub.Experiment_ID[pub.Experiment_ID.ne('')]); exp_ids=set(exp.Experiment_ID[exp.Experiment_ID.ne('')])
print('pub exp absent experiment ledger',pub_exp-exp_ids)
p0_pub=set(p0.publication_id[p0.publication_id.ne('')]); pub_ids=set(pub.Publicacion_ID[pub.Publicacion_ID.ne('')])
print('p0 publication ids absent publication log',p0_pub-pub_ids)
print('historical periods')
hist=pd.read_csv(root/'Operations/Research/Historical_Performance_Individuals.csv',dtype=str).fillna('')
print(hist['period'].value_counts().to_string())
print('historical meta duplicate',hist.meta_id.duplicated().sum())
